GET http://localhost/models/{{$randomInt}}
Accept: application/json

###

GET http://localhost/models/{{$randomInt}}
Accept: application/json

###

GET http://localhost/models/{{$randomInt}}
Accept: application/json

###

GET http://localhost/models
Accept: application/json

###
