server:
  forward-headers-strategy: framework
  shutdown: graceful

management:
  health:
    probes:
      enabled: true

spring:
  application:
    name: demo-service

logging:
  level:
    io.github.cepr0: debug
